### ISSUE TITLE
option to ignore the border reset (using road-schematics with border)

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquaredSuggestions#63]
I would like configure a road-schematic (same before and after claim) without any block-change of the border.

On older versions block_claimed & block are ignored If that was undefined. Currently PlotSquared **set AIR blocks** in this position and **override my border schematic**.

```
[...]
    wall:
      filling: cyan_terracotta
      height: 62
      block_claimed: ''
      block: ''
[...]
    schematic:
      specify_on_claim: false
      on_claim: false
      file: ''
      schematics:
      - ''
[...]
```

schematic in
- PlotSquared/schematics/GEN_ROAD_SCHEMATIC/<worldname>/intersection.schem
- PlotSquared/schematics/GEN_ROAD_SCHEMATIC/<worldname>/sideroad.schem

before (normal world-generation with ROAD schematics):
![2019-10-04_02 21 46](https://user-images.githubusercontent.com/4140635/66172980-4d495580-e64e-11e9-8bce-88c9ab23735f.png)

after "/p claim":
![2019-10-04_02 21 59](https://user-images.githubusercontent.com/4140635/66172998-5d613500-e64e-11e9-9ffd-502c4d46494e.png)

**[REQUIRED] Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**post from here:** https://github.com/IntellectualSites/PlotSquared/issues/2521
